### ISSUE TITLE
Incorrect temperature range & brightness problem

### ISSUE THREAD

**Issue by Rjaap** [sbidy/wiz_light#51]
Referring to [Bulb Test Report] #49

Color temperature range is 2000K tot 5000K, however in HA I can't set the slider lower than 25000K. Also HA thinks this bulb does 6500K as max temperature. In addition, I can't set the slider for brightness to it's lowest setting, meaning the lowest setting is lower than the actual bulb ability.

**Comment by Rjaap** [comment]
Same here, tried it, didn't work. Still can't set the slider to the lowest white temperature.

**Comment by Rjaap** [comment]
In addition, I took a  look at the changes you made. I guess it still takes the default values instead of the values you added for the two lights.

**Comment by sbidy** [comment]
Please clone the [bulbconfig Tree](https://github.com/sbidy/wiz_light/tree/bulbconfig).
It should be fixed with the `bulblibrary.yaml`

**Comment by ChrisLizon** [comment]
@sbidy I was able to pull the new branch, and it now lets me set my bulbs down to 454 mired, (2200K), However, when I set the bulb to this color, the slider jumps back to 400 mired or 2500K, and that's where the bulb gets set. If I change the bulb via the Wiz app, the status correctly updates to 454 mired. 

I am not sure if there is anything I can do to capture debug output to help troubleshoot this. I'm pretty savvy but still learning the Home Assistant architecture, YAML, and I haven't touched Python in 8 years but hopefully it's like riding a bike.

**Comment by sbidy** [comment]
Ok, so I tested it again with my bulb her and do some debugging. The Value will be set correctly. 
Can you please check the following:
**First: Made a service / container stop and start - don't use "restart".**
1.  Please check the installed `pywizlight` version - because there was an change in the value validation. Maybe update manually to the latest 0.3.4. via pip.
2. Please set the slider in the UI to the lowest value (warm). An fire a `echo '{"method":"getPilot","params":{}}' | nc -u -w 1 <The IP of the bulb> 38899` - Please look for the "temp" value. What is listed here?
3. Set the value with the slider and check it with the App without changing anything. What is the app showing?
4. Set the lowest value in the app and made the `echo '{"method":"getPilot","params":{}}' | nc -u -w 1 <The IP of the bulb> 38899` again. What it the "temp" value her?

It can be a possible bug in the HA UI (there were some problems in the past with low kelvin values).
If I set the slider to the warmest value a request was create with this value. My bulb is only supporting 2700K - that is way my slider will bump back to a 2666K value. That is an normal behavior because the UI will read the info from the bulb dynamically and the min. value which can be provided from the bulb is 2700K (2200K --send to bulb--> Bulb rewrites the value to 2700K <-- reads the vaule -- HA UI).

Overall the "translation" from kelvin to mired are not accurate. It can be possible to have not exact same value which was selected.

**Comment by ChrisLizon** [comment]
1. Please check the installed pywizlight version - because there was an change in the value validation. Maybe update manually to the latest 0.3.4. via pip.

pywizlight was still at version 0.3.2, upgrading and restarting home asssitant from the UI didn't fix it, nor did stopping and starting it via my shell. (Home-Assistant is running in a V env under CentOS). 

2. Please set the slider in the UI to the lowest value (warm). An fire a echo '{"method":"getPilot","params":{}}' | nc -u -w 1 <The IP of the bulb> 38899 - Please look for the "temp" value. What is listed here?

`
{"method":"getPilot","env":"pro","result":{"mac":"a8bb50bbdcd1","rssi":-73,"src":"","state":true,"sceneId":0,"temp":2500,"dimming":53}}
`

3. Set the value with the slider and check it with the App without changing anything. What is the app showing?

App is showing ~2500K white

4. Set the lowest value in the app and made the echo '{"method":"getPilot","params":{}}' | nc -u -w 1 <The IP of the bulb> 38899 again. What it the "temp" value her?

App is showing ~2200K white


`
{"method":"getPilot","env":"pro","result":{"mac":"a8bb50bbdcd1","rssi":-73,"src":"","state":true,"sceneId":0,"temp":2200,"dimming":53}}
`

**Comment by sbidy** [comment]
Ok - so one last question you are using the `"moduleName":"ESP17_SHTW9_01"` ?

**Comment by ChrisLizon** [comment]
@sbidy, No, I'm using ESP01_SHRGB1C_31 mentioned in #56. Sorry if there was any confusion.

**Comment by sbidy** [comment]
Ah, ok. So I'll try to find out if this is an UI error from HA or a issue from my implementation. If I look into the debug messages, all seems to be working and the correct kelvin will be transmitted to the bulb.

**Comment by ChrisLizon** [comment]
I tried to check the debug messages by adding:

```
logger:
    default: critical
    logs:
        #log level for a custom component
        custom_components.wiz_light: debug
```
to my configuration.yaml, 

I get one line that says 
```
Dec 08 12:22:49 HomeAssistant.local python[214612]: 2020-12-08 12:22:49 INFO (MainThread) [custom_components.wiz_light.light] Initiate the WiZ bulb as ESP01_SHRGB1C_31
```
But after that all I see is this message over and over. Perhaps I'm looking in the wrong place. I will try to dig deeper. 
```
Dec 08 12:25:10 HomeAssistant.local python[214612]: 2020-12-08 12:25:10 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.8.105] updating state
Dec 08 12:25:10 HomeAssistant.local python[214612]: 2020-12-08 12:25:10 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.8.105] updated state: True
```

**Comment by sbidy** [comment]
so now I checked the behavior again and also add some better debug output for controlling the kelvin settings.
Now it looks like the following output from my bulb:
```
homeassistant    | 2020-12-08 22:21:28 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.178.95] kelvin changed and send to bulb: 2202
homeassistant    | 2020-12-08 22:21:29 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.178.95] updated state: True
homeassistant    | 2020-12-08 22:21:29 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.178.95] kelvin from the bulb: 2700
```
The wiz_light will try to set the 2202 kelvin to the lamp. But this will be set this to the lowest possible value (in this case the lamp only supports 2700k). This value will be returned to the HA. That's why my slider will bump back.

Can you pleas pull again and have a look into the debug messages again? Now it should show this details.
Please ensure that you pull the **bulbconfig Tree**. :octocat:

**Comment by ChrisLizon** [comment]
```
2020-12-08 17:04:23 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.8.105] kelvin changed and send to bulb: 2272
2020-12-08 17:04:24 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.8.105] updated state: True
2020-12-08 17:04:24 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.8.105] kelvin from the bulb: 2500
````

😥

I will do some more testing later when I am home and  I can use my app. My bulbs are not exposed to the internet. 

I am starting to wonder if this is something broken in the firmware.

**Comment by sbidy** [comment]
Yes maybe - but I'll also try to debug this, but unfortunately don't have one of these bulbs 😞. Maybe that is an issue of the pywizlight or the UDP-API itself.

**Comment by ChrisLizon** [comment]
```
2020-12-08 18:48:19 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.8.105] updated state: True
2020-12-08 18:48:19 DEBUG (MainThread) [custom_components.wiz_light.light] [wizlight 192.168.8.105] kelvin from the bulb: 2200
```

The bulb will definitely go down to 2200, I have set it via the app and I can see it inside Home Assistant, as expected. I plan to set up a spare access point so I can set up wireshark between my phone and my bulbs, and maybe I can capture something interesting.

**Comment by sbidy** [comment]
This was also one point on my (long) "ToDo-List" 📓 to trace the traffic between the bulb and the HA. I'm also relay interested in how the app communicate with the bulb. Because there should also be a REST-API beside the UDP-API.

**Comment by ChrisLizon** [comment]
So I did some packet capture, which was interesting. It looks like somewhere between home assistant, wiz_light, and pywizlight the setPilot message never gets sent with a temp value below 2500.

```
0000   a8 bb 50 ae c6 35 00 15 5d ae 40 00 08 00 45 00   ..P..5..].@...E.
0010   00 5b 38 62 40 00 40 11 6e 10 c0 a8 09 5a c0 a8   .[8b@.@.n....Z..
0020   09 75 c4 a0 97 f3 00 47 1d 8e 7b 22 6d 65 74 68   .u.....G..{"meth
0030   6f 64 22 3a 20 22 73 65 74 50 69 6c 6f 74 22 2c   od": "setPilot",
0040   20 22 70 61 72 61 6d 73 22 3a 20 7b 22 73 74 61    "params": {"sta
0050   74 65 22 3a 20 74 72 75 65 2c 20 22 74 65 6d 70   te": true, "temp
0060   22 3a 20 32 35 30 30 7d 7d                        ": 2500}}
````

nicely formatted: `{"method": "setPilot", "params": {"state": true, "temp": 2500}}`

Here's an example when I set the color temp to 2200 kelvin via the app. 

```
0000   00 04 96 83 57 a0 a8 3e 0e 4a a3 f4 08 00 45 00   ....W..>.J....E.
0010   00 52 36 02 40 00 40 11 71 73 c0 a8 09 6c c0 a8   .R6.@.@.qs...l..
0020   08 69 b6 79 97 f3 00 3e 05 1f 7b 22 70 61 72 61   .i.y...>..{"para
0030   6d 73 22 3a 7b 22 74 65 6d 70 22 3a 32 32 30 30   ms":{"temp":2200
0040   7d 2c 22 69 64 22 3a 31 36 33 2c 22 6d 65 74 68   },"id":163,"meth
0050   6f 64 22 3a 22 73 65 74 50 69 6c 6f 74 22 7d 0a   od":"setPilot"}.

```

using NC to pass the string `{"params":{"temp":2200},"id":163,"method":"setPilot"}` sets the bulb to 2200k, and I can confirm via both the Wiz app and the Home Asssitant UI.

**Comment by sbidy** [comment]
Great !! I've to transfer this issue to the pywizlight repo. I think there life the 👹 because this integration is creating the UDP package. HA -> wiz_light -> pywizligh -> bulb

**Comment by sbidy** [comment]
There we go ... https://github.com/sbidy/pywizlight/commit/fd38f61e44ad0ff030fbc81574026cb1da954e31
So in the older releases there are this "limitation" implemented. But in the current pip package this should be fixed.
Can you please verify the version an update to `0.3.4` - this should fix the issue.

**Comment by ChrisLizon** [comment]
Hmm, that's bizzare. I upgraded my pywizlight the other day when I pulled the bulbconfig tree. I still had the buffer open in screen....

```(homeassistant) homeassistant@hass /srv/homeassistant $ pip install pywizlight --upgrade
Collecting pywizlight
  Downloading pywizlight-0.3.4-py3-none-any.whl (9.5 kB)
Requirement already satisfied, skipping upgrade: asyncio-dgram in ./lib/python3.8/site-packages (from pywizlight) (1.1.1)
Installing collected packages: pywizlight
  Attempting uninstall: pywizlight
    Found existing installation: pywizlight 0.3.2
    Uninstalling pywizlight-0.3.2:
      Successfully uninstalled pywizlight-0.3.2
Successfully installed pywizlight-0.3.4
```

I'm pretty sure I'm in the correct Virtual Enviroment.....

I will have to do more digging once the kiddo goes to bed.

**Comment by ChrisLizon** [comment]
Well this is frustrating. I did install pywizlight 0.3.4. However, every time I restart Home Assistant it gets downgraded...

```
(homeassistant) homeassistant@hass /srv/homeassistant $ pip show pywizlight
Name: pywizlight
Version: 0.3.4
Summary: A python connector for WiZ light bulbs (e.g SLV Play)
Home-page: https://github.com/sbidy/pywizlight
Author: Stephan Traub
Author-email: sbidy@hotmail.com
License: UNKNOWN
Location: /srv/homeassistant/lib/python3.8/site-packages
Requires: asyncio-dgram
Required-by:
(homeassistant) homeassistant@hass /srv/homeassistant $ pip show pywizlight
Name: pywizlight
Version: 0.3.2
Summary: A python connector for WiZ light bulbs (e.g SLV Play)
Home-page: https://github.com/sbidy/pywizlight
Author: Stephan Traub
Author-email: sbidy@hotmail.com
License: UNKNOWN
Location: /srv/homeassistant/lib/python3.8/site-packages
Requires: asyncio-dgram, asyncio
Required-by:
(homeassistant) homeassistant@hass /srv/homeassistant $
````
Something is weird in my install....

**Comment by ChrisLizon** [comment]
Found it... submitted pull request #60

**Comment by sbidy** [comment]
Oh man - thank you for the support. I missed to change the version. 😢 
So maybe I have to purchase one of these "special" bulbs for my final testing steps.

Thank you for the contribution and digging in to that 🤟 🚀
